name: 'Build docker container'
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ${{ GITHUB_WORKSPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker
        run: |
            echo "Checking docker installation"
            if command -v docker &> /dev/null; then
                echo "Docker installation found"
            else
                echo "Docker installation not found. Docker will be installed"
                curl -fsSL https://get.docker.com | sh
            fi
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Login to Gitea container registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.claeyscloud.com
          username: nologin
          password: ${{ secrets.PACKAGE_TOKEN }}
      - name: Login to DockerHub container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
            labels: |
                org.opencontainers.image.title=epg-info
                org.opencontainers.image.description=Docker image of https://github.com/iptv-org/epg
                org.opencontainers.image.authors=Davidquinonescl
                org.opencontainers.image.documentation=https://git.claeyscloud.com/david/epg-info-docker/src/branch/main/README.md
            images: |
                davidquinonescl/epg-info
                git.claeyscloud.com/david/epg-info
            tags: |
               type=semver,pattern={{raw}}
               type=sha
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}            
          labels: ${{ steps.meta.outputs.labels }}
      #- name: Update docker Hub Description
      #  uses: https://github.com/peter-evans/dockerhub-description@v5
      #  with:
      #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #    repository: davidquinonescl/epg-info
             
